### ISSUE TITLE
Do not open url input field by default in the Browser

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1639]
When I am switching tabs (Wallet-Browser) then the URL input field is active by default (with the keyboard). It should not be active by default. 

![browser-active-url-input](https://user-images.githubusercontent.com/51817359/95731419-cc209780-0c7f-11eb-8b5c-6862105162e6.gif)

**Comment by JamesSmartCell** [comment]
This should be fixed in the latest release on play store. Can you try it?

**Comment by colourfreak** [comment]
No, this is not done. And this is causing another problem like a keyboard in the wallet tab if you switch tabs too fast. 
![2020-12-01 08 57 59](https://user-images.githubusercontent.com/51817359/100716125-8e570a00-33b8-11eb-9afb-4e2db07347f8.jpg)

**Comment by colourfreak** [comment]
The problem still exists. 

https://user-images.githubusercontent.com/51817359/132854957-2677031e-67c0-45ec-b328-8aaea7403a37.mp4

**Comment by mpaschenko** [comment]
@JamesSmartCell we can close it as it's merged already
