### ISSUE TITLE
App crashes when connecting to Ethereum/Matic bridge

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1889]
Android 3.31 (154)

![2021-06-02-110321](https://user-images.githubusercontent.com/51817359/120459562-93f9d080-c398-11eb-90d8-176c1395ff32.gif)

**Comment by AW-STJ** [comment]
For me, the app is not crashing but cannot connect to the bridge as WalletConnect appears to be broken

![image](https://user-images.githubusercontent.com/61957841/120566774-54dc8580-c453-11eb-9c14-f2822d10db28.png)

https://wallet.matic.network/bridge/

**Comment by colourfreak** [comment]
I requested on their Discord. They said we should integrate matic.js SDK.

**Comment by JamesSmartCell** [comment]
Good news; this is fixed in the forthcoming release.

**Comment by roguetr** [comment]
Hi, this issue still seems to be occurring on 3.33. All other dapps for the most part work but matic bridge and wallet get stuck at either "metamask not installed" or walletconnect no passing through.

**Comment by JamesSmartCell** [comment]
I finally managed to reproduce this issue --- thanks for your patience.
