### ISSUE TITLE
Ropsten test net transfer failed

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2283]
The e2e test failed, when transfer from A wallet to B
 wallet, the result shows it is A to A.
I guess it maybe related to this code in SendActivity:
` final String txDestAddress = token.isEthereum() ? txSendAddress : token.getAddress(); //either another address, or ERC20 Token address`

**Comment by JamesSmartCell** [comment]
Yes this got into the repo but wasn't released - can you sync with master it was fixed.

**Comment by JamesSmartCell** [comment]
Good catch though :)

**Comment by seabornlee** [comment]
That's great! Sorry I just checked the SendActivity file and seen it looks the same so I assumed it was not fixed yet.
When I merge master branch, I got one error when fetch token price with CoinGecko’s API:
```
2021-12-14 16:50:01.774 9204-9413/io.stormbird.wallet W/System.err: java.net.SocketTimeoutException: failed to connect to api.coingecko.com/74.86.228.110 (port 443) from /10.0.2.15 (port 44570) after 10000ms
2021-12-14 16:50:01.774 9204-9413/io.stormbird.wallet W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
2021-12-14 16:50:01.775 9204-9413/io.stormbird.wallet W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:180)
2021-12-14 16:50:01.775 9204-9413/io.stormbird.wallet W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2021-12-14 16:50:01.776 9204-9413/io.stormbird.wallet W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2021-12-14 16:50:01.776 9204-9413/io.stormbird.wallet W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2021-12-14 16:50:01.777 9204-9413/io.stormbird.wallet W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2021-12-14 16:50:01.778 9204-9413/io.stormbird.wallet W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2021-12-14 16:50:01.778 9204-9413/io.stormbird.wallet W/System.err:     at java.net.Socket.connect(Socket.java:621)
2021-12-14 16:50:01.779 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
2021-12-14 16:50:01.779 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2021-12-14 16:50:01.780 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2021-12-14 16:50:01.781 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2021-12-14 16:50:01.781 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2021-12-14 16:50:01.781 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2021-12-14 16:50:01.782 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2021-12-14 16:50:01.783 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2021-12-14 16:50:01.783 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-12-14 16:50:01.784 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2021-12-14 16:50:01.784 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-12-14 16:50:01.784 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2021-12-14 16:50:01.784 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-12-14 16:50:01.785 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2021-12-14 16:50:01.785 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2021-12-14 16:50:01.785 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2021-12-14 16:50:01.786 9204-9413/io.stormbird.wallet W/System.err:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2021-12-14 16:50:01.786 9204-9413/io.stormbird.wallet W/System.err:     at com.alphawallet.app.service.TickerService.lambda$fetchCoinGeckoChainPrices$2$TickerService(TickerService.java:193)
2021-12-14 16:50:01.787 9204-9413/io.stormbird.wallet W/System.err:     at com.alphawallet.app.service.-$$Lambda$TickerService$sLiBuywHpXMbaKu34PQ59-V21v4.call(Unknown Source:2)
2021-12-14 16:50:01.787 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
2021-12-14 16:50:01.788 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.788 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
2021-12-14 16:50:01.788 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
2021-12-14 16:50:01.788 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
2021-12-14 16:50:01.789 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.789 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
2021-12-14 16:50:01.789 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
2021-12-14 16:50:01.789 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
2021-12-14 16:50:01.790 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.790 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
2021-12-14 16:50:01.790 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.791 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
2021-12-14 16:50:01.791 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.791 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
2021-12-14 16:50:01.791 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.792 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
2021-12-14 16:50:01.792 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.792 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
2021-12-14 16:50:01.793 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-12-14 16:50:01.793 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2021-12-14 16:50:01.793 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2021-12-14 16:50:01.793 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2021-12-14 16:50:01.794 9204-9413/io.stormbird.wallet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2021-12-14 16:50:01.794 9204-9413/io.stormbird.wallet W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-12-14 16:50:01.794 9204-9413/io.stormbird.wallet W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-12-14 16:50:01.794 9204-9413/io.stormbird.wallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-14 16:50:01.794 9204-9413/io.stormbird.wallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-14 16:50:01.795 9204-9413/io.stormbird.wallet W/System.err:     at java.lang.Thread.run(Thread.java:920
```
I guess maybe it was caused by the free plan limitation?
`Our Free API* has a rate limit of 50 calls/minute. Need something more flexible and powerful? View our API plans now.`

**Comment by JamesSmartCell** [comment]
Yes, this happens I think because you are behind GFW and recently all the crypto price oracles have been blocked (I have a server operating out of ShenZhen; up until about September it was reading the coingecko price oracles, but after that it couldn't get through). 

Is this causing a crash? Or is this an error dump? It shouldn't cause a crash; could you submit a separate PR that bypasses the price oracle for tokens if the socket connection fails, if it is crashing.

I'm not sure how to fix the actual issue - I guess the point is you're not supposed to.

**Comment by seabornlee** [comment]
Thx James. Yes, it does't crash.
I can run tests on CI server, it should work well.
