### ISSUE TITLE
C++ build Error

### ISSUE THREAD

**Issue by slobodandeveloper** [AlphaWallet/alpha-wallet-android#3316]
I got custom app source forked from this repo.
And then, I got this error building custom app project on recent android studio.
I think that the error occurred because of wrong configuration on my local.
Please check it and guide me how to configure exactly.
Regards.

```
[CXX1429] error when building with cmake using D:\Workspace\defi.cryptomi.wallet\source_code\app\src\main\cpp\CMakeLists.txt: -- Configuring incomplete, errors occurred!
See also "D:/Workspace/defi.cryptomi.wallet/source_code/app/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    @echo off
    "C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HD:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\src\\main\\cpp" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=28" ^
      "-DANDROID_PLATFORM=android-28" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_ANDROID_NDK=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_C_FLAGS=-DIFKEY=\\""""da3717f25f824cc1baa32d812386d93f""\\"" -DOSKEY=\\""""...""\\"" -DPSKEY=\\""""""\\"" -DASKEY=\\""""HFDDY5BNKGXBB82DE2G8S64C3C41B76PYI""\\"" -DWALLETCONNECT_PROJECT_ID=\\""""40c6071febfd93f4fe485c232a8a4cd9""\\""" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\build\\intermediates\\cxx\\Debug\\5t1v11j6\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\build\\intermediates\\cxx\\Debug\\5t1v11j6\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BD:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\.cxx\\Debug\\5t1v11j6\\x86" ^
      -GNinja
  from D:\Workspace\defi.cryptomi.wallet\source_code\app
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 9/25/2023 4:06:04 AM.
    Project "D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" on node 1 (default targets).
    SetBuildDefaultEnvironmentVariables:
      ANDROID_HOME=
      ANT_HOME=
      JAVA_HOME=
      NDK_ROOT=
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(358,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|x86. [D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    Done Building Project "D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) -> 
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(358,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|x86. [D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    
        0 Warning(s)
        1 Error(s)
    
    Time Elapsed 00:00:00.96
    

  Exit code: 1
```

**Comment by JamesSmartCell** [comment]
Hi @slobodandeveloper, yes you get this error if you haven't set up the NDK. I've had it a few times and it's really frustrating!

I generally do this:

1. Install NDK: 25.1.8937393
2. Ensure Gradle-JDK is jbr-17 JetBrains version 17.0.6 (Settings/Build, Execution, Deployment/Build Tools/Gradle)
3. Setup Environment vars like this:
JAVA_HOME=C:\Users\<USER NAME>\.jdks\corretto-17.0.7
PATH=...;C:\Users\<USER_NAME>\.jdks\corretto-17.0.7/bin;...
4. Build/Refresh Linked C++ projects

I don't have ANDROID_HOME set up in my environment vars.

Hopefully this will be sufficient to get you going.

**Comment by slobodandeveloper** [comment]
Hi, @JamesSmartCell , thanks for your reply.
![Screenshot_5](https://github.com/AlphaWallet/alpha-wallet-android/assets/75948775/ff011dbd-63fd-44c0-b18b-fe66b9a168a8)

I have already installed the NDK before the error occurred.

And then, I am not sure how to build / refresh linked c++ projects.
Would you explain about it in detail?

Regards.

**Comment by JamesSmartCell** [comment]
Are you building from Android Studio? In the top menu click 'Build' then 'Refresh linked C++ projects".

**Comment by slobodandeveloper** [comment]
Nothing changed.

Perhaps, should I install and configure Visual Studio to compile the c++ codes?

I would like to share my recent error after I configured Visual Studio Community 2017

```
[CXX1429] error when building with cmake using D:\Workspace\defi.cryptomi.wallet\source_code\app\src\main\cpp\CMakeLists.txt: -- Configuring incomplete, errors occurred!
See also "D:/Workspace/defi.cryptomi.wallet/source_code/app/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    @echo off
    "C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HD:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\src\\main\\cpp" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=28" ^
      "-DANDROID_PLATFORM=android-28" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_ANDROID_NDK=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_C_FLAGS=-DIFKEY=\\""""da3717f25f824cc1baa32d812386d93f""\\"" -DOSKEY=\\""""...""\\"" -DPSKEY=\\""""""\\"" -DASKEY=\\""""HFDDY5BNKGXBB82DE2G8S64C3C41B76PYI""\\"" -DWALLETCONNECT_PROJECT_ID=\\""""40c6071febfd93f4fe485c232a8a4cd9""\\""" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\build\\intermediates\\cxx\\Debug\\5t1v11j6\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\build\\intermediates\\cxx\\Debug\\5t1v11j6\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BD:\\Workspace\\defi.cryptomi.wallet\\source_code\\app\\.cxx\\Debug\\5t1v11j6\\x86" ^
      -GNinja
  from D:\Workspace\defi.cryptomi.wallet\source_code\app
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 9/26/2023 4:25:33 PM.
    Project "D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" on node 1 (default targets).
    SetBuildDefaultEnvironmentVariables:
      ANDROID_HOME=C:\ProgramData\Microsoft\AndroidSDK\25
      ANT_HOME=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Apps\apache-ant-1.9.3
      JAVA_HOME=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25
      NDK_ROOT=C:\\Microsoft\AndroidNDK64\android-ndk-r15c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(358,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|x86. [D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    Done Building Project "D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) -> 
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(358,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|x86. [D:\Workspace\defi.cryptomi.wallet\source_code\app\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    
        0 Warning(s)
        1 Error(s)
    
    Time Elapsed 00:00:00.14
    

  Exit code: 1

```

**Comment by JamesSmartCell** [comment]
Those environment vars might be sending it to the wrong places.

I've had this error in the past, I fixed it by ensuring the JAVA_HOME and the grade jdk are the same.

You need corretto jdk 17, your JAVA_HOME should point there. I don't think you need Visual Studio

**Comment by slobodandeveloper** [comment]
Hi, @JamesSmartCell ,
Thanks for your helps.

And then, I still face the problem now.
Would you help me to keep in touch in whatsapp?
this is my whatsapp number : +13308001121

I would like to get helps via real time chatting.

Regards.

**Comment by slobodandeveloper** [comment]
Hi, @JamesSmartCell 

I have configured the system environments as you mentioned.
And then, I got this error, in CMakeCache.txt

```
> Task :app:configureCMakeDebug[x86_64]
C/C++: CMake Warning (dev) in CMakeLists.txt:
C/C++:   No project() command is present.  The top-level CMakeLists.txt file must
C/C++:   contain a literal, direct call to the project() command.  Add a line of
C/C++:   code such as
C/C++:     project(ProjectName)
C/C++:   near the top of the file, but after cmake_minimum_required().
C/C++:   CMake is pretending there is a "project(Project)" command on the first
C/C++:   line.
C/C++: This warning is for project developers.  Use -Wno-dev to suppress it.
C/C++: CMake Error in CMakeLists.txt:
C/C++:   Generator
C/C++:     Visual Studio 17 2022
C/C++:   could not find specified instance of Visual Studio:
C/C++:     C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild

> Task :app:configureCMakeDebug[x86_64] FAILED
```

I am not sure why it needs me to install visual studio to compile C++ codes.
Would you explain about it?

**Comment by JamesSmartCell** [comment]
This warning is expected. This is what I get when I 'Refresh linked C++ projects':

```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 44 ms
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
C/C++: CMake Warning (dev) in CMakeLists.txt:
C/C++:   No project() command is present.  The top-level CMakeLists.txt file must
C/C++:   contain a literal, direct call to the project() command.  Add a line of
C/C++:   code such as
C/C++:     project(ProjectName)
C/C++:   near the top of the file, but after cmake_minimum_required().
C/C++:   CMake is pretending there is a "project(Project)" command on the first
C/C++:   line.
C/C++: This warning is for project developers.  Use -Wno-dev to suppress it.
```

I think the error about Visual Studio is because it's trying to use the wrong cmake install. I previously had the same error, however it turned out to be a version mismatch. Maybe remove Visual Studio from your PATH:

```
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\<USER_NAME>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<USER_NAME>\AppData\Roaming\npm;C:\Program Files\gradle\bin;C:\Users\<USER_NAME>\.jdks\corretto-17.0.7\bin;
```

**Comment by JamesSmartCell** [comment]
Hi @slobodandeveloper can you try this:

Find your Android SDK directory, and specifically the instance of cmake. I have v3.22.1:

```C:\Users\<USER_NAME>\AppData\Local\Android\Sdk\cmake\3.22.1\bin```

go to your alpha-wallet-android\app directory:

```~\StudioProjects\alpha-wallet-android\app```

Now try this command:

```C:\Users\<USER_NAME>\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake .\src\main\cpp```

Let me know what this produces. In theory it should populate your cpp directory so it now should look like this:

<img width="161" alt="image" src="https://github.com/AlphaWallet/alpha-wallet-android/assets/12689544/dfad3fda-f790-4cd4-a9c5-35bc233ff266">

Here is what my build looks like:

```
~\StudioProjects\alpha-wallet-android\app [master ≡ +0 ~1 -0 !]> C:\Users\<USER_NAME>\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake .\src\main\cpp
-- Building for: Visual Studio 15 2017
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.16.27051.0
-- The CXX compiler identification is MSVC 19.16.27051.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/<USER_NAME>/StudioProjects/alpha-wallet-android/app
```

**Comment by JamesSmartCell** [comment]
I think we should be able to get to the bottom of this. Once your build is working I'll add to the build instructions in the readme. If you can generate the "includes" directory for the cpp build then your gradle build will skip that stage and the build should continue ok.

**Comment by JamesSmartCell** [comment]
Bear in mind also, that in our test suite it starts from a blank slate each time. 

It installs Java 17 Corretto, then installs the SDK, then NDK, then it issues a gradle build. This builds the C++ aspect of the app without any issues.

Therefore, the issue you're seeing is most likely in the PATH settings.

**Comment by slobodandeveloper** [comment]
Hi, @JamesSmartCell , thanks for your continuous reply.

I followed your suggestion : https://github.com/AlphaWallet/alpha-wallet-android/issues/3316#issuecomment-1736400001
and it generates some files like this.
![Screenshot_1](https://github.com/AlphaWallet/alpha-wallet-android/assets/75948775/a664ca69-9609-4a06-8663-d78949ff06f9)

and then, I faced another error like this.
```
[CXX1429] error when building with cmake using D:\Workspace\Cryptomi\cryptomi.wallet\source_code\app\src\main\cpp\CMakeLists.txt: -- Android: Selected unified Clang toolchain
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Users/leoDroid/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/leoDroid/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - broken
-- Configuring incomplete, errors occurred!
See also "D:/Workspace/Cryptomi/cryptomi.wallet/source_code/app/CMakeFiles/CMakeOutput.log".
See also "D:/Workspace/Cryptomi/cryptomi.wallet/source_code/app/CMakeFiles/CMakeError.log".

C++ build system [configure] failed while executing:
    @echo off
    "C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HD:\\Workspace\\Cryptomi\\cryptomi.wallet\\source_code\\app\\src\\main\\cpp" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=28" ^
      "-DANDROID_PLATFORM=android-28" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_ANDROID_NDK=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=C:\\Users\\leoDroid\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_C_FLAGS=-DIFKEY=\\""""da3717f25f824cc1baa32d812386d93f""\\"" -DOSKEY=\\""""...""\\"" -DPSKEY=\\""""""\\"" -DASKEY=\\""""HFDDY5BNKGXBB82DE2G8S64C3C41B76PYI""\\"" -DWALLETCONNECT_PROJECT_ID=\\""""40c6071febfd93f4fe485c232a8a4cd9""\\""" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Workspace\\Cryptomi\\cryptomi.wallet\\source_code\\app\\build\\intermediates\\cxx\\Debug\\5t1v11j6\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Workspace\\Cryptomi\\cryptomi.wallet\\source_code\\app\\build\\intermediates\\cxx\\Debug\\5t1v11j6\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BD:\\Workspace\\Cryptomi\\cryptomi.wallet\\source_code\\app\\.cxx\\Debug\\5t1v11j6\\x86" ^
      -GNinja
  from D:\Workspace\Cryptomi\cryptomi.wallet\source_code\app
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Users/leoDroid/AppData/Local/Android/Sdk/cmake/3.22.1/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Users/leoDroid/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/Workspace/Cryptomi/cryptomi.wallet/source_code/app/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:\Users\leoDroid\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe cmTC_3a845.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && ninja: error: loading 'build.ninja': The system cannot find the file specified.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt
```

I will try to reinstall android studio and uninstall visual studio again.
Thanks.

**Comment by slobodandeveloper** [comment]
Hi, @JamesSmartCell .

After I uninstall visual studio and I run the command C:\Users\<USER_NAME>\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake .\src\main\cpp
It shows the error like this.

I think that the error occurred because it didn't find c/c++ compiler.

Did you install MingW for c/c++ compiler to your pc and configure the path for PATH environment variable?

```
D:\Workspace\Cryptomi\defi.cryptomi.wallet\source_code\app\src\main\cpp>cmake .
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/Workspace/Cryptomi/defi.cryptomi.wallet/source_code/app/src/main/cpp/CMakeFiles/CMakeOutput.log".
```

**Comment by JamesSmartCell** [comment]
No, it should all be contained within the NDK.

Try this.

1. Uninstall Visual Studio
2. Remove all references to 'Visual Studio' in your PATH - both local user and system
3. Open Android Studio, go to tools and make sure you have 3.22 installed:

<img width="624" alt="image" src="https://github.com/AlphaWallet/alpha-wallet-android/assets/12689544/6b2fbd51-4f66-4e8e-9601-e3a2aa642816">

Ensure you have the NDK:

<img width="629" alt="image" src="https://github.com/AlphaWallet/alpha-wallet-android/assets/12689544/32ba5a96-dc29-4f99-a7c6-2cf19a97b610">

Now ensure there's no other references to cmake in the PATH (eg NVIDIA Physx)

Now try to execute this line, from your D:/Workspace/alpha-wallet-android/app directory
```C:\Users\leodroid\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake .\src\main\cpp```

Try to get this running on a vanilla AlphaWallet clone first, then you should be able to get it running on your build.

Of course, you can also strip this out! You'll need to stub the API class like this:

```JAVA
public class KeyProviderJNIImpl implements KeyProvider
{
    @Override
    public String getInfuraKey()
    {
        return EthereumNetworkBase.DEFAULT_INFURA_KEY;
    }

    @Override
    public String getBSCExplorerKey()
    {
        return null;
    }

    @Override
    public String getAnalyticsKey()
    {
        return null;
    }

    @Override
    public String getEtherscanKey()
    {
        return null;
    }

    @Override
    public String getPolygonScanKey()
    {
        return null;
    }

    @Override
    public String getAuroraScanKey()
    {
        return null;
    }

    @Override
    public String getCovalentKey()
    {
        return null;
    }

    @Override
    public String getKlaytnKey()
    {
        return null;
    }

    @Override
    public String getSecondaryInfuraKey()
    {
        return null;
    }

    @Override
    public String getTertiaryInfuraKey()
    {
        return null;
    }

    @Override
    public String getRampKey()
    {
        return null;
    }

    @Override
    public String getOpenSeaKey()
    {
        return null;
    }

    @Override
    public String getMailchimpKey()
    {
        return null;
    }

    @Override
    public String getCoinbasePayAppId()
    {
        return null;
    }

    @Override
    public String getWalletConnectProjectId()
    {
        return null;
    }

    @Override
    public String getInfuraSecret()
    {
        return null;
    }

    @Override
    public String getUnstoppableDomainsKey()
    {
        return null;
    }

    @Override
    public String getOkLinkKey()
    {
        return null;
    }

    @Override
    public String getBlockPiBaobabKey()
    {
        return null;
    }

    @Override
    public String getBlockPiCypressKey()
    {
        return null;
    }

    @Override
    public String getBlockNativeKey()
    {
        return null;
    }

    @Override
    public String getSmartPassKey()
    {
        return null;
    }

    @Override
    public String getSmartPassDevKey()
    {
        return null;
    }
}
```

Then simply strip out the cpp directory and 
```
externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
```

from the build.gradle.

Might save you a bit of headache. The cpp file is used to provide a way for us to remove the API keys from the github.

**Comment by JamesSmartCell** [comment]
Then, when you obtain your own Infura, Blockscout, Etherscan, OpenSea etc API keys you can bundle them in a swappable file

**Comment by slobodandeveloper** [comment]
Hi, @JamesSmartCell .
I got the error when I run it on windows.

And the project source works well on mac without any issues.

Thanks for all.

**Comment by JamesSmartCell** [comment]
> Hi, @JamesSmartCell .
> I got the error when I run it on windows.
> 
> And the project source works well on mac without any issues.
> 
> Thanks for all.

Yes, I think it's due to the PATH settings and versions of cmake or compilers being found before the NDK tools are found. If you have a clean setup it should build ok.

**Comment by JamesSmartCell** [comment]
Closing as it's now fixed
